[sncast.default]
url = "http://127.0.0.1:5050/rpc"
accounts-file = "accounts.json"
account = "devnet0"

[sncast.devnet]
url = "http://127.0.0.1:5050/rpc"
accounts-file = "accounts.json"
account = "devnet0"