[sncast.testnet]
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_10/gu3D3rKyivv6bhmb3UbyUSYxThLz7C_c"
accounts-file = "accounts_testnet.json"
account = "deployer"
fee-token = "strk"
